# Generated by Django 5.2.13 on 2026-04-21 15:49

import organizations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='join_code',
            field=models.CharField(default=organizations.models.generate_code, max_length=10, unique=True),
        ),
    ]
