# Generated by Django 5.2.13 on 2026-04-21 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ogranization',
            new_name='organization',
        ),
    ]
